# This file has been deprecated as its functionality is now handled by release-on-merge.yml
# The NPM token validation is performed during the npm publish step in release-on-merge.yml
# This file will be removed in a future update.
name: Release Doctor
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release_doctor:
    name: release doctor
    runs-on: ubuntu-latest
    if: false  # Disabled as functionality is now in release-on-merge.yml

    steps:
      - run: echo "This workflow is deprecated and will be removed. NPM token validation is now handled by release-on-merge.yml"
