name: Release Doctor
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release_doctor:
    name: release doctor
    runs-on: ubuntu-latest
    if: github.repository == 'vlm-run/vlmrun-node-sdk' && 
        (github.event_name == 'push' || 
         github.event_name == 'workflow_dispatch' || 
         startsWith(github.head_ref, 'release-please') || 
         github.head_ref == 'next' || 
         github.ref_type == 'tag')

    steps:
      - uses: actions/checkout@v4

      - name: Check release environment
        run: |
          bash ./bin/check-release-environment
        env:
          NPM_TOKEN: ${{ secrets.VLM_NPM_TOKEN || secrets.NPM_TOKEN }}
